SongProject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name='homepage'),
    path('songs/',include('songs.urls',namespace='songs')),
    path('accounts/',include('accounts.urls',namespace='accounts'))
]

songs/urls.py
from django.urls import path
from . import views
app_name = 'songs'
urlpatterns = [

    path('spotify/login',views.login,name='spotify-login'),
    path('',views.song_index,name='index'),
    path('random/',views.getRandomSong,name='random'),
    path('playlist/',views.getPlaylist,name='playlist'),
    path('playsong/',views.playsong,name='playsong'),
    path('stopsong/',views.stopsong,name='stopsong'),
    path('playsong/<track_uri>',views.playPlaylistSong,name='play_playlistsong'),

]

songs/forms.py
from django import forms 


class RandomSong(forms.Form):
    GENRE_CHIOCES = (
        ('country','Country'),
        ('alternative','Alternative'),
        ('hip-hop','Hip-Hop'),
        ('r-n-b','R&B'),
        ('indie','Indie'),
        ('rock','Rock'),
        ('pop','Pop'),
        ('chill','Chill'),
        ('sad','Sad'),
        ('romance','Romance'),
        ('disney','Disney'),
    )
    genre = forms.ChoiceField(choices=GENRE_CHIOCES,label='Genre')



class PlaylistGeneratorForm(forms.Form):
    GENRE_CHIOCES = (
        ('country','Country'),
        ('alternative','Alternative'),
        ('hip-hop','Hip-Hop'),
        ('r-n-b','R&B'),
        ('indie','Indie'),
        ('rock','Rock'),
        ('pop','Pop'),
        ('chill','Chill'),
        ('sad','Sad'),
        ('romance','Romance'),
        ('disney','Disney'),
    )

    genre1 = forms.ChoiceField(choices=GENRE_CHIOCES,label="My favorite genre")
    genre2 = forms.ChoiceField(choices=GENRE_CHIOCES,label="A close second")
    genre3 = forms.ChoiceField(choices=GENRE_CHIOCES,label='Explore this genre')
    favorite_song = forms.CharField(label='Finally, enter the name of your current favorite song')

    def clean(self):
        one, two, three = self.cleaned_data['genre1'], self.cleaned_data['genre2'], self.cleaned_data['genre3']
        if one == two or one == three or two == three:
            raise forms.ValidationError("Make sure all of your genres are different!")
        return super().clean()

songs/views.py
import requests
import random
from django.shortcuts import render, redirect 
from django.contrib.auth.decorators import login_required
from django.conf import settings
from spotipy import SpotifyOAuth
from . import forms 

#USE JSON= for post data
BASE_URL = 'https://api.spotify.com/v1/'
USER_ID = None

############# RANDOM SONG #############
@login_required
def getRandomSong(request):
    #needed_headers
    spheaders = {'Authorization': "Bearer " + request.session['access_token']}
    form = forms.RandomSong(request.POST or None)
    context = {
        'form':form,
    }
    
    if request.method == 'POST':
        if form:
            if form.is_valid():
                gen = form.cleaned_data['genre']

                #url to get songs w a certain genre
                res = requests.get(BASE_URL + 'recommendations?seed_genres=' + gen, headers=spheaders)
                res = res.json()
            
                random_idx = random.randint(0,len(res['tracks']))
                track_uri = res['tracks'][random_idx]['uri']
                request.session['track_uri'] = track_uri
                res = requests.get(BASE_URL + 'tracks/' + res['tracks'][random_idx]['id'], headers=spheaders).json()
                request.session['track_name'] = res['name']
                request.session['artist_name'] = res['artists'][0]['name']

                
                return render(request,'songs/partials/random_song_playable.html')
        else:
            return render(request,'songs/partials/random_song.html',context)

    return render(request,'songs/partials/random_song.html',context)


############### PLAYLIST GENERATOR ###############
@login_required
def getPlaylist(request):
    #get rid of overhead in session variables 
    # gathered from other request
    if 'track_uri' in request.session:
        del request.session['track_uri']

    spheaders = {'Authorization': "Bearer " + request.session['access_token']}
    form = forms.PlaylistGeneratorForm(request.POST or None)
    context = {
        'form':form,
    }

    if request.method == "POST":
        if form:
            if form.is_valid():
                songs = []
                gen1 = form.cleaned_data['genre1']
                gen2 = form.cleaned_data['genre2']
                gen3 = form.cleaned_data['genre3']
                favorite_song = "%20".join(form.cleaned_data['favorite_song'].split(' '))
                search_song = requests.get(BASE_URL + 'search?q=' + favorite_song + "&type=track",headers=spheaders).json()
                search_song = search_song['tracks']['items'][0]['id']
                rec1 =  requests.get(BASE_URL + 'recommendations?seed_genres=' + gen1, headers=spheaders).json()
                rec2 =  requests.get(BASE_URL + 'recommendations?seed_genres=' + gen2, headers=spheaders).json()
                rec3 =  requests.get(BASE_URL + 'recommendations?seed_genres=' + gen3, headers=spheaders).json()
                rec4 = requests.get(BASE_URL + 'recommendations?seed_tracks=' + search_song,headers=spheaders).json()
                for i in range(15):
                    if i < 5:
                        track_uri = rec1['tracks'][i]['uri']
                        song_info = requests.get(BASE_URL + 'tracks/' + rec1['tracks'][i]['id'],headers=spheaders).json()
                        song_name = song_info['name']
                        artist_name = song_info['artists'][0]['name']
                        songs.append((track_uri,song_name,artist_name))
                    elif i < 9:
                        track_uri = rec2['tracks'][i]['uri']
                        song_info = requests.get(BASE_URL + 'tracks/' + rec2['tracks'][i]['id'],headers=spheaders).json()
                        song_name = song_info['name']
                        artist_name = song_info['artists'][0]['name']
                        songs.append((track_uri,song_name,artist_name))
                        
                    elif i < 12:
                        track_uri = rec3['tracks'][i]['uri']
                        song_info = requests.get(BASE_URL + 'tracks/' + rec3['tracks'][i]['id'],headers=spheaders).json()
                        song_name = song_info['name']
                        artist_name = song_info['artists'][0]['name']
                        songs.append((track_uri,song_name,artist_name))
                    else:
                        track_uri = rec4['tracks'][i]['uri']
                        song_info = requests.get(BASE_URL + 'tracks/' + rec4['tracks'][i]['id'],headers=spheaders).json()
                        song_name = song_info['name']
                        artist_name = song_info['artists'][0]['name']
                        songs.append((track_uri,song_name,artist_name))
    

            
                context = {
                    'songs': songs,

                }
                return render(request,'songs/partials/generate_playlist_playable.html',context)  
        else:
            return render(request,'songs/partials/generate_playlist.html',context)


    return render(request,'songs/partials/generate_playlist.html',context)


def playPlaylistSong(request):
    to_play = {"uris":''}


    return render(request,'songs/partials/stop_playlistsong.html')

def stopPlaylistSong(request):



    return render(request,'songs/partials/play_playlist.song.html')


########### PLAYBACK CONTROL RANDOM SONG#############
def playsong(request):
    if 'track_uri' in request.session:
        to_play = {"uris": [request.session['track_uri'] ]}
        spheaders = {'Authorization': "Bearer " + request.session['access_token']}
        requests.put(BASE_URL + 'me/player/play',headers=spheaders,json=to_play)
        del request.session['track_uri']
    else:
        spheaders = {'Authorization': "Bearer " + request.session['access_token']}
        requests.put(BASE_URL + 'me/player/play',headers=spheaders)
        
    return render(request,'songs/partials/stop_song.html')


def stopsong(request):
    spheaders = {'Authorization': "Bearer " + request.session['access_token']}
    requests.put(BASE_URL + 'me/player/pause',headers=spheaders)
    return render(request,'songs/partials/play_song.html')


################ MAIN HOME PAGE #################
@login_required
def song_index(request):
    #needed headers
    spheaders = {'Authorization': "Bearer " + request.session['access_token']}

    #adding username to screen 
    res = requests.get(BASE_URL + 'me/', headers=spheaders).json()
    request.session['user_id'] = res['id']
    request.session['user_name'] = res['display_name'].split(" ")[0]

    return render(request,'songs/init.html')





############### LOGIN AND OAUTH HANDLING ####################
def login(request):
    sp_auth = oauth()
    redirect_url = sp_auth.get_authorize_url()
    token = sp_auth.get_access_token()
    access_token = token['access_token']
    refresh_token = token['refresh_token']
    expires_in = token['expires_in']
    request.session['access_token'] = access_token
    request.session['refresh_token'] = refresh_token
    request.session['expires_in'] = expires_in
    request.session.modified = True
    return redirect(redirect_url)


def oauth():
    scope = 'user-read-playback-state user-modify-playback-state user-read-currently-playing playlist-modify-public playlist-modify-private'
    sp_auth = SpotifyOAuth(
        scope = scope,
        client_id=settings.CLIENT_ID,
        client_secret=settings.CLIENT_SECRET,
        redirect_uri=settings.REDIRECT_URI,
    )
    return sp_auth
    

songs/templates/songs/partials/generate_playlist.html
<div hx-target='this' hx-swap='outerHTML'>
    <form>
        <h2>Select Your Top Three Genres</h2>
        <h4>We will make a custom, 15 song playlist designed just for your taste!</h4>
        {% csrf_token %}
        {{ form.as_p }}
        <button hx-post="{% url 'songs:playlist' %}" class='styled-button'>Make My Playlist!</button>
</div>

songs/templates/songs/partials/generate_playlist_playable.html
<div hx-target='this' hx-swap='outerHTML'>
    <h1 style='text-align: center; color: var(--light); margin-bottom: 5px;'>Below are the songs we think you'd love! </h1>
    {% for song in songs %}
        <h2 style='text-align: center; color: var(--light); font-style: italic;'> {{song.1}} </h2>
        <p style='text-align: center; color: var(--light);'> By: </p>
        <h3 style='text-align: center; color: var(--light); font-style: italic;'> {{song.2}} </h3>
        <div hx-target='this' hx-swap='outerHTML'>
            <div class='three-button-center'>
                <button hx-post="{% url 'songs:play_playlistsong' track_uri=song.0 %}"class='styled-button'>Play Song on Your Device</button>
            </div>
        </div>
        <hr>
    {% endfor %}
    <div class='three-button-center' style='margin-top: 20px;'>
        <button hx-post="{% url 'songs:playlist' %}" class='styled-button'>Make another playlist!</button>
       
    </div>
    
</div>

songs/templates/songs/partials/play_song.html
<div hx-target='this' hx-swap='outerHTML' style='margin-bottom: 10px;'>
    <div class='three-button-center'>
        <button hx-post="{% url 'songs:playsong' %}"class='styled-button'>Resume Playback</button>
    </div>
</div>

songs/templates/songs/partials/random_song.html
<div hx-target='this' hx-swap='outerHTML'>
    <form method="POST">
        <h2>Select a Genre!</h2>
        <p>For the best experience, open your spotify app! </p>
        {% csrf_token %}
        {{ form.as_p}}
        <button hx-post="{% url 'songs:random' %}"class='styled-button'>Find me a song!</button>
    </form>
</div>

songs/templates/songs/partials/random_song_playable.html
<div hx-target='this' hx-swap='outerHTML'>
    <h1 style='text-align: center; color: var(--light);'> You should listen to... </h1>
    <h3 style='text-align: center; color: var(--light); font-style: italic;'> {{ request.session.track_name}} by {{ request.session.artist_name }}</h3>
    <div hx-target='this' hx-swap='outerHTML' style='margin-bottom: 10px;'>
        <div class='three-button-center'>
        <button hx-post="{% url 'songs:playsong' %}"class='styled-button'>Play Song on Your Device</button>
        </div>
    </div>
    <div class='three-button-center'>
        <button hx-post="{% url 'songs:random' %}" class='styled-button'>Generate Another!</button>
    </div>
</div>

songs/templates/songs/partials/stop_song.html
<div hx-target='this' hx-swap='outerHTML' style='margin-bottom: 10px;'>
    <div class='three-button-center'>
        <button hx-post="{% url 'songs:stopsong' %}"class='styled-button'>Stop playback</button>
    </div>
</div>