SongProject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name='homepage'),
    path('songs/',include('songs.urls',namespace='songs')),
    path('accounts/',include('accounts.urls',namespace='accounts'))
]

accounts/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from . import forms

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html',authentication_form=forms.MyLoginForm),name='login'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

songs/urls.py
from django.urls import path
from . import views
app_name = 'songs'
urlpatterns = [

    path('spotify/login',views.login,name='spotify-login'),
    path('',views.song_index,name='index'),
    path('random/',views.getRandomSong,name='random'),
    path('playlist/',views.getPlaylist,name='playlist'),
    path('playsong/',views.playsong,name='playsong'),
    path('stopsong/',views.stopsong,name='stopsong'),
    path('playsong/<track_uri>',views.playPlaylistSong,name='play_playlistsong'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <title>Song Recommender</title>
</head>
<body>
    
    <nav>
        <div class="container">
            <h1 class="logo">Songify</h1>

            <div class='menu'>
                {% if user.is_authenticated %}
                <a href="{% url 'homepage' %}" class='is-active' id="homepage">Home</a>
                <a href="{% url 'songs:spotify-login' %}">Songify</a>
                <a href="#" id="connect">Connect</a>
                <a href="{% url 'accounts:logout' %}" id="logout">Logout</a>
                {% else %}
                <a href="{% url 'homepage' %}" class="is-active" id="homepage">Home</a>
                <a href="#" id="connect">Connect</a>
                <a href="{% url 'accounts:signup' %}" id="signup">Sign Up</a>
                <a href="{% url 'accounts:login' %}" id="login">Login</a>
                {% endif %}
            </div>

            <button class='hamburger'>
                <span></span>
                <span></span>
                <span></span>
            </button>
        </div>
    </nav>

    <div class='mobile-menu'>
        {% if user.is_authenticated %}
        <a href="#">Home</a>
        <a href="{% url 'songs:spotify-login' %}">Songify</a>
        <a href="#">Connect</a>
        <a href="#">Logout</a>
        {% else %}
        <a href="#">Home</a>
        <a href="#">Connect</a>
        <a href="#">Sign Up</a>
        <a href="#">Login</a>
        {% endif %}
    </div>
    

    <div class="body_content">
    {% block content %}

    {% endblock content %}
    <div>
    <script src="https://unpkg.com/htmx.org@1.8.4" integrity="sha384-wg5Y/JwF7VxGk4zLsJEcAojRtlVp1FKKdGy1qN+OMtdq72WRvX/EdRdqg/LOhYeV" crossorigin="anonymous"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
    <script src="{% static 'js/master.js' %}"></script>
   
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% block content %}
<h1 class='title-text'> Enhancing Music<h1> 
<h3 class='slogan-text'> one song at a time </h3>
{% if user.is_authenticated %}
<div class='center-button'>
<a href="{% url 'songs:spotify-login' %}"><button class='styled-home-button'>Get Started</button></a>
</div>
{% else %}
<div class='center-button'>
<a href='{% url "accounts:signup" %}'><button class='styled-home-button'> Sign Up</button></a>
</div>
{% endif %}
{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>What a world</h1>
{% endblock content %}